# -*- coding: utf-8 -*-
"""trained_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFxgUwlcgnJyCn6mQJ6HOIV2ZW9SmAKk
"""

!pip install ultralytics --upgrade -q

from google.colab import files
uploaded = files.upload()

!unzip -q ms-mitosis-detection2.yolov8.zip -d mitosis_data

!ls

!ls mitosis_data

import os
from glob import glob

def keep_only_n_images(folder, n):
    images = sorted(glob(f"{folder}/images/*.jpg"))[:n]
    labels = [img.replace("images", "labels").replace(".jpg", ".txt") for img in images]

    # Remove excess images and labels
    for f in glob(f"{folder}/images/*.jpg"):
        if f not in images:
            os.remove(f)
    for f in glob(f"{folder}/labels/*.txt"):
        if f not in labels:
            os.remove(f)

# Apply trimming
keep_only_n_images("mitosis_data/train", 2000)
keep_only_n_images("mitosis_data/valid", 20)

print("Dataset trimmed to 2000 train and 20 valid.")

from ultralytics import YOLO

# Load the pre-trained YOLOv8 nano model
model = YOLO("yolov8n.pt")

# Train on your trimmed dataset
model.train(
    data="mitosis_data/data.yaml",  # path to your data.yaml file
    epochs=20,
    imgsz=416,
    batch=8,
    name="mitosis-nano"
)

from ultralytics import YOLO

# Load the trained model
model = YOLO("runs/detect/mitosis-nano/weights/best.pt")

# Run inference and save predictions
results = model.predict(
    source="mitosis_data/valid/images",  # path to validation images
    conf=0.25,                           # confidence threshold
    save=True,                           # save images with bounding boxes
    imgsz=416                            # image size used during training
)

from ultralytics import YOLO

# Load your trained model (update the path if needed)
model = YOLO("runs/detect/mitosis-nano/weights/best.pt")

# Run prediction on validation set
model.predict(source="mitosis_data/valid/images", save=True, imgsz=416)

import os
import cv2
import matplotlib.pyplot as plt

# Change this to your actual path
pred_dir = "runs/detect/predict"

# Get the first image name
pred_files = sorted(os.listdir(pred_dir))
first_img = [f for f in pred_files if f.endswith('.jpg')][0]

# Paths
original_path = os.path.join("mitosis_data/valid/images", first_img)
predicted_path = os.path.join(pred_dir, first_img)

# Load images
original = cv2.imread(original_path)
predicted = cv2.imread(predicted_path)

# Convert BGR to RGB
original = cv2.cvtColor(original, cv2.COLOR_BGR2RGB)
predicted = cv2.cvtColor(predicted, cv2.COLOR_BGR2RGB)

# Show side by side
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(original)
plt.title(f"Plain Image - {first_img}")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(predicted)
plt.title("Bounding Boxes (YOLO Predictions)")
plt.axis("off")

plt.tight_layout()
plt.show()

from ultralytics import YOLO

model = YOLO("runs/detect/mitosis-nano/weights/best.pt")  # or "last.pt" if needed

# Run predictions again with `save=True`
results = model.predict(source="mitosis_data/valid/images", save=True, conf=0.25)

import os
import cv2
import matplotlib.pyplot as plt

# Paths
pred_dir = "runs/detect/predict"
orig_dir = "mitosis_data/valid/images"

# Number of images to show
num_images = 5

# Get predicted image filenames
image_files = sorted([f for f in os.listdir(pred_dir) if f.endswith(".jpg")])[:num_images]

# Plot
plt.figure(figsize=(15, num_images * 3))

for i, file in enumerate(image_files):
    # Load original and predicted images
    original_img = cv2.imread(os.path.join(orig_dir, file))
    predicted_img = cv2.imread(os.path.join(pred_dir, file))

    # Convert to RGB
    original_img = cv2.cvtColor(original_img, cv2.COLOR_BGR2RGB)
    predicted_img = cv2.cvtColor(predicted_img, cv2.COLOR_BGR2RGB)

    # Plain image
    plt.subplot(num_images, 2, i * 2 + 1)
    plt.imshow(original_img)
    plt.title(f"Plain Image - {file}")
    plt.axis("off")

    # Predicted image with boxes
    plt.subplot(num_images, 2, i * 2 + 2)
    plt.imshow(predicted_img)
    plt.title("Predicted - Bounding Boxes")
    plt.axis("off")

plt.tight_layout()
plt.show()

